# Generated by Django 2.1.7 on 2019-04-13 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RfqSupplierDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RfqSupplierHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_no', models.CharField(max_length=100)),
                ('_from', models.CharField(max_length=100)),
                ('attn', models.CharField(max_length=100)),
                ('follow_up', models.DateField(blank=True, verbose_name='Date')),
                ('follow_up_expiry', models.DateField(blank=True, verbose_name='Date')),
                ('supplier_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='rfqsupplierdetail',
            name='rfq_supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.RfqSupplierHeader'),
        ),
    ]
