# Generated by Django 2.2 on 2019-04-22 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationHeaderSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_ref', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('attn', models.CharField(max_length=100)),
                ('_from', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('prc_basis', models.CharField(max_length=100)),
                ('yrref', models.CharField(max_length=100)),
                ('leadtime', models.CharField(max_length=100)),
                ('validity', models.CharField(max_length=100)),
                ('payment', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('follow_up', models.DateField(blank=True, verbose_name='Follow Up')),
                ('show_notification', models.BooleanField(default=False)),
                ('supplier_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RfqSupplierHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_no', models.CharField(max_length=100)),
                ('_from', models.CharField(max_length=100)),
                ('attn', models.CharField(max_length=100)),
                ('follow_up', models.DateField(blank=True, verbose_name='Date')),
                ('follow_up_expiry', models.DateField(blank=True, verbose_name='Date')),
                ('supplier_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RfqSupplierDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('remarks', models.CharField(max_length=100)),
                ('rfq_supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.RfqSupplierHeader')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationDetailSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quotation_header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.QuotationHeaderSupplier')),
            ],
        ),
    ]
