# Generated by Django 2.2 on 2019-04-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationdetailsupplier',
            name='unit',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
