# Generated by Django 2.2 on 2019-04-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_quotationdetailsupplier_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationheadersupplier',
            name='show_notification',
            field=models.CharField(max_length=100),
        ),
    ]
