# Generated by Django 2.2 on 2019-04-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_auto_20190424_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationdetailsupplier',
            name='quotation_header_id',
        ),
    ]
