# Generated by Django 2.2 on 2019-04-25 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_remove_quotationdetailsupplier_quotation_header_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationdetailsupplier',
            name='quotation_header_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='supplier.QuotationHeaderSupplier'),
            preserve_default=False,
        ),
    ]
