# Generated by Django 2.2 on 2019-04-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_quotationdetailsupplier_quotation_header_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationdetailsupplier',
            name='quotation_header_id',
        ),
    ]
